CREATE TABLE `ab_tests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`campaignId` int,
	`name` varchar(256) NOT NULL,
	`abType` enum('subject_line','content','send_time','sender_name') NOT NULL,
	`abStatus` enum('draft','running','completed') NOT NULL DEFAULT 'draft',
	`variants` json,
	`winnerVariant` varchar(8),
	`winnerMetric` enum('open_rate','click_rate','conversion') DEFAULT 'open_rate',
	`sampleSize` int DEFAULT 20,
	`results` json,
	`startedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `ab_tests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `activities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`contactId` int,
	`companyId` int,
	`dealId` int,
	`activityType` varchar(64) NOT NULL,
	`subject` varchar(512),
	`body` text,
	`callOutcome` varchar(64),
	`callType` varchar(32),
	`callDuration` int,
	`emailTo` varchar(320),
	`emailFrom` varchar(320),
	`emailCc` text,
	`emailOpened` boolean DEFAULT false,
	`emailClicked` boolean DEFAULT false,
	`meetingStartTime` bigint,
	`meetingEndTime` bigint,
	`meetingLocation` varchar(512),
	`meetingAttendees` text,
	`meetingOutcome` varchar(256),
	`metadata` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_keys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`keyHash` varchar(128) NOT NULL,
	`keyPrefix` varchar(16) NOT NULL,
	`permissions` json,
	`lastUsedAt` bigint,
	`expiresAt` bigint,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `api_keys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`domain` varchar(256),
	`companyOwnerId` int,
	`companyType` varchar(128),
	`companyEmail` varchar(320),
	`phone` varchar(64),
	`streetAddress` varchar(512),
	`addressLine2` varchar(256),
	`city` varchar(128),
	`stateRegion` varchar(128),
	`postalCode` varchar(32),
	`country` varchar(128),
	`timezone` varchar(64),
	`industry` varchar(128),
	`numberOfEmployees` varchar(64),
	`annualRevenue` varchar(128),
	`description` text,
	`businessClassification` varchar(64),
	`foundedYear` varchar(8),
	`leadSource` varchar(128) DEFAULT 'CRM',
	`leadStatus` varchar(128) DEFAULT 'Cold',
	`lastEmailOpened` bigint,
	`lastEmailClicked` bigint,
	`lastContactedDate` bigint,
	`lastActivityDate` bigint,
	`nextActivityDate` bigint,
	`timesContacted` int DEFAULT 0,
	`lastMeetingBooked` bigint,
	`creditTerms` varchar(128),
	`paymentStatus` varchar(64),
	`lanePreferences` text,
	`tmsIntegrationStatus` varchar(64),
	`recordSource` varchar(128),
	`importSource` varchar(128),
	`facebookPage` varchar(512),
	`facebookBusinessUrl` varchar(512),
	`twitterHandle` varchar(128),
	`linkedinUrl` varchar(512),
	`youtubeUrl` varchar(512),
	`parentId` int,
	`website` varchar(512),
	`tags` json,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128),
	`jobTitle` varchar(256),
	`companyId` int,
	`contactOwnerId` int,
	`email` varchar(320),
	`companyPhone` varchar(64),
	`directPhone` varchar(64),
	`mobilePhone` varchar(64),
	`faxNumber` varchar(64),
	`linkedinUrl` varchar(512),
	`websiteUrl` varchar(512),
	`streetAddress` varchar(512),
	`addressLine2` varchar(256),
	`city` varchar(128),
	`stateRegion` varchar(128),
	`postalCode` varchar(32),
	`country` varchar(128),
	`timezone` varchar(64),
	`lifecycleStage` varchar(64) DEFAULT 'lead',
	`leadStatus` varchar(128) DEFAULT 'Cold',
	`leadSource` varchar(128) DEFAULT 'CRM',
	`leadScore` int DEFAULT 0,
	`originalSource` varchar(256),
	`originalSourceDrill1` varchar(256),
	`originalSourceDrill2` varchar(256),
	`latestSource` varchar(256),
	`latestSourceDrill1` varchar(256),
	`latestSourceDrill2` varchar(256),
	`lastActivityDate` bigint,
	`lastContactedDate` bigint,
	`nextActivityDate` bigint,
	`timesContacted` int DEFAULT 0,
	`recentEmailOpenedDate` bigint,
	`recentEmailClickedDate` bigint,
	`emailSubscriptionStatus` varchar(32) DEFAULT 'subscribed',
	`unsubscribeDate` bigint,
	`gdprConsentStatus` varchar(32),
	`communicationPreferences` json,
	`firstPageSeen` varchar(512),
	`lastPageSeen` varchar(512),
	`websiteSessions` int DEFAULT 0,
	`pageViewCount` int DEFAULT 0,
	`lastSeenAt` bigint,
	`firstConversion` varchar(256),
	`firstConversionDate` bigint,
	`mostRecentConversion` varchar(256),
	`mostRecentConversionDate` bigint,
	`recordSource` varchar(128),
	`recordSourceDetail1` varchar(256),
	`recordSourceDetail2` varchar(256),
	`isImported` boolean DEFAULT false,
	`twitterHandle` varchar(128),
	`facebookProfile` varchar(512),
	`instagramProfile` varchar(512),
	`decisionMakerRole` varchar(128),
	`department` varchar(128),
	`freightVolume` varchar(128),
	`customerType` varchar(64),
	`paymentResponsibility` varchar(128),
	`preferredContactMethod` varchar(64),
	`tags` json,
	`avatarUrl` varchar(512),
	`notes` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`pipelineId` int NOT NULL,
	`stageId` int NOT NULL,
	`contactId` int,
	`companyId` int,
	`name` varchar(256) NOT NULL,
	`dealValue` bigint DEFAULT 0,
	`currency` varchar(8) DEFAULT 'USD',
	`status` enum('open','won','lost') NOT NULL DEFAULT 'open',
	`priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
	`expectedCloseDate` bigint,
	`closedAt` bigint,
	`lostReason` text,
	`notes` text,
	`tags` json,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `domain_health` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`domain` varchar(256) NOT NULL,
	`spfStatus` enum('pass','fail','missing','unknown') NOT NULL DEFAULT 'unknown',
	`dkimStatus` enum('pass','fail','missing','unknown') NOT NULL DEFAULT 'unknown',
	`dmarcStatus` enum('pass','fail','missing','unknown') NOT NULL DEFAULT 'unknown',
	`dmarcPolicy` varchar(32),
	`mxServer` varchar(256),
	`mxIp` varchar(64),
	`reputationScore` int DEFAULT 50,
	`warmupPhase` int DEFAULT 0,
	`dailySendLimit` int DEFAULT 50,
	`totalSentToday` int DEFAULT 0,
	`lastCheckedAt` bigint,
	`notes` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `domain_health_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`templateId` int,
	`name` varchar(256) NOT NULL,
	`subject` varchar(512),
	`fromName` varchar(256),
	`fromEmail` varchar(320),
	`htmlContent` text,
	`campaignStatus` enum('draft','scheduled','sending','sent','paused','cancelled') NOT NULL DEFAULT 'draft',
	`segmentId` int,
	`scheduledAt` bigint,
	`sentAt` bigint,
	`totalRecipients` int DEFAULT 0,
	`delivered` int DEFAULT 0,
	`opened` int DEFAULT 0,
	`clicked` int DEFAULT 0,
	`bounced` int DEFAULT 0,
	`unsubscribed` int DEFAULT 0,
	`spamReports` int DEFAULT 0,
	`spamScore` int,
	`abTestId` int,
	`abVariant` varchar(8),
	`tags` json,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `email_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int,
	`smtpAccountId` int,
	`contactId` int NOT NULL,
	`toEmail` varchar(320) NOT NULL,
	`fromEmail` varchar(320),
	`fromName` varchar(256),
	`subject` varchar(512),
	`htmlContent` text,
	`queueStatus` varchar(32) NOT NULL DEFAULT 'pending',
	`attempts` int NOT NULL DEFAULT 0,
	`lastError` text,
	`sentAt` bigint,
	`openedAt` bigint,
	`clickedAt` bigint,
	`bouncedAt` bigint,
	`bounceType` varchar(32),
	`createdAt` bigint NOT NULL,
	CONSTRAINT `email_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`subject` varchar(512) NOT NULL,
	`htmlContent` text NOT NULL,
	`jsonContent` json,
	`category` varchar(128),
	`thumbnail` varchar(512),
	`isSystem` boolean NOT NULL DEFAULT false,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `email_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lead_status_options` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`label` varchar(128) NOT NULL,
	`color` varchar(32),
	`sortOrder` int NOT NULL DEFAULT 0,
	`isDefault` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `lead_status_options_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pipeline_stages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pipelineId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`stageOrder` int NOT NULL,
	`probability` int NOT NULL DEFAULT 0,
	`color` varchar(32) DEFAULT '#6366f1',
	CONSTRAINT `pipeline_stages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `pipelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `segments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`filters` json,
	`contactCount` int DEFAULT 0,
	`isDynamic` boolean NOT NULL DEFAULT true,
	`lastRefreshedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `segments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `smtp_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`emailAddress` varchar(320) NOT NULL,
	`displayName` varchar(256),
	`domain` varchar(256) NOT NULL,
	`smtpHost` varchar(256) NOT NULL,
	`smtpPort` int NOT NULL DEFAULT 587,
	`smtpUsername` varchar(320) NOT NULL,
	`smtpPassword` varchar(512) NOT NULL,
	`useTls` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`dailyLimit` int NOT NULL DEFAULT 385,
	`sentToday` int NOT NULL DEFAULT 0,
	`lastSentAt` bigint,
	`lastResetDate` varchar(16),
	`healthStatus` varchar(32) DEFAULT 'healthy',
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `smtp_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(512) NOT NULL,
	`taskType` varchar(64) DEFAULT 'to_do',
	`dueDate` bigint,
	`dueTime` varchar(16),
	`assignedTo` int,
	`priority` enum('low','medium','high') NOT NULL DEFAULT 'medium',
	`description` text,
	`taskStatus` enum('not_started','completed') NOT NULL DEFAULT 'not_started',
	`queue` varchar(128),
	`reminderDate` bigint,
	`reminderSent` boolean DEFAULT false,
	`contactId` int,
	`companyId` int,
	`dealId` int,
	`completedAt` bigint,
	`completedBy` int,
	`outcome` text,
	`isRecurring` boolean DEFAULT false,
	`recurringFrequency` varchar(32),
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
--> statement-breakpoint
CREATE TABLE `webhook_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`webhookId` int NOT NULL,
	`event` varchar(128) NOT NULL,
	`payload` json,
	`responseStatus` int,
	`responseBody` text,
	`success` boolean NOT NULL DEFAULT false,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `webhook_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `webhooks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`url` varchar(1024) NOT NULL,
	`events` json,
	`secret` varchar(256),
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTriggeredAt` bigint,
	`failureCount` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `webhooks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workflows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`triggerConfig` json,
	`steps` json,
	`wfStatus` enum('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
	`enrolledCount` int DEFAULT 0,
	`completedCount` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `workflows_id` PRIMARY KEY(`id`)
);
