CREATE TABLE `battle_cards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`prospectId` int NOT NULL,
	`title` varchar(512) NOT NULL,
	`companyOverview` text,
	`personInsights` text,
	`painPoints` json,
	`talkingPoints` json,
	`competitorIntel` text,
	`recommendedApproach` text,
	`objectionHandlers` json,
	`triggerContext` text,
	`urgencyLevel` varchar(500) DEFAULT 'medium',
	`isRead` boolean NOT NULL DEFAULT false,
	`isArchived` boolean NOT NULL DEFAULT false,
	`generatedAt` bigint NOT NULL,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `battle_cards_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broker_filings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`dotNumber` varchar(32),
	`mcNumber` varchar(32),
	`legalName` varchar(512) NOT NULL,
	`dbaName` varchar(512),
	`contactName` varchar(256),
	`contactEmail` varchar(320),
	`contactPhone` varchar(64),
	`phyStreet` varchar(512),
	`phyCity` varchar(128),
	`phyState` varchar(64),
	`phyZip` varchar(16),
	`filingType` enum('new','renewal','reinstatement') NOT NULL,
	`authorityType` enum('broker','carrier','freight_forwarder','broker_carrier') DEFAULT 'broker',
	`authorityStatus` enum('active','pending','revoked','inactive','not_authorized') DEFAULT 'pending',
	`filingDate` bigint,
	`effectiveDate` bigint,
	`insuranceRequired` boolean DEFAULT true,
	`bondSuretyName` varchar(256),
	`bondAmount` int,
	`processedStatus` enum('pending','prospect_created','campaign_enrolled','skipped') DEFAULT 'pending',
	`prospectId` int,
	`campaignId` int,
	`scanBatchId` varchar(64),
	`rawData` json,
	`notes` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `broker_filings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compliance_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`emailQueueId` int,
	`campaignId` int,
	`toEmail` varchar(320) NOT NULL,
	`fromEmail` varchar(320) NOT NULL,
	`hasPhysicalAddress` boolean NOT NULL,
	`hasUnsubscribeLink` boolean NOT NULL,
	`hasOneClickUnsubscribe` boolean NOT NULL,
	`hasIdentifiedAsAd` boolean NOT NULL,
	`subjectLineClean` boolean NOT NULL,
	`recipientNotSuppressed` boolean NOT NULL,
	`recipientHasConsent` boolean NOT NULL,
	`spfAligned` boolean NOT NULL,
	`dkimAligned` boolean NOT NULL,
	`dmarcAligned` boolean NOT NULL,
	`compliancePassed` boolean NOT NULL,
	`failureReasons` json,
	`recipientProvider` varchar(32),
	`wasSent` boolean NOT NULL DEFAULT false,
	`sentAt` bigint,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `compliance_audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `domain_sending_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`domain` varchar(256) NOT NULL,
	`provider` varchar(32) NOT NULL,
	`statDate` varchar(16) NOT NULL,
	`sent` int NOT NULL DEFAULT 0,
	`delivered` int NOT NULL DEFAULT 0,
	`bounced` int NOT NULL DEFAULT 0,
	`complaints` int NOT NULL DEFAULT 0,
	`opens` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`unsubscribes` int NOT NULL DEFAULT 0,
	`bounceRate` int DEFAULT 0,
	`complaintRate` int DEFAULT 0,
	`openRate` int DEFAULT 0,
	`isPaused` boolean NOT NULL DEFAULT false,
	`pauseReason` varchar(256),
	`createdAt` bigint NOT NULL,
	CONSTRAINT `domain_sending_stats_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ghost_sequence_steps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sequenceId` int NOT NULL,
	`stepOrder` int NOT NULL,
	`delayDays` int NOT NULL DEFAULT 1,
	`subject` varchar(512),
	`bodyTemplate` text,
	`aiGenerated` boolean NOT NULL DEFAULT true,
	`useDigitalTwin` boolean NOT NULL DEFAULT true,
	`toneOverride` varchar(64),
	`totalSent` int DEFAULT 0,
	`totalOpened` int DEFAULT 0,
	`totalReplied` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `ghost_sequence_steps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ghost_sequences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`stylisticFingerprint` json,
	`seqStatus` varchar(32) NOT NULL DEFAULT 'draft',
	`totalEnrolled` int DEFAULT 0,
	`totalReplied` int DEFAULT 0,
	`totalConverted` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `ghost_sequences_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `integration_credentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`service` varchar(64) NOT NULL,
	`apiKey` text NOT NULL,
	`apiSecret` text,
	`baseUrl` varchar(512),
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTestedAt` bigint,
	`testStatus` varchar(32) DEFAULT 'untested',
	`testMessage` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `integration_credentials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prospect_outreach` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prospectId` int NOT NULL,
	`sequenceId` int,
	`stepId` int,
	`fromEmail` varchar(320),
	`toEmail` varchar(320),
	`subject` varchar(512),
	`body` text,
	`outreachStatus` varchar(32) NOT NULL DEFAULT 'draft',
	`sentAt` bigint,
	`openedAt` bigint,
	`clickedAt` bigint,
	`repliedAt` bigint,
	`bouncedAt` bigint,
	`replyContent` text,
	`intentAnalysis` json,
	`smtpAccountId` int,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `prospect_outreach_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prospect_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prospectId` int NOT NULL,
	`firmographicScore` int DEFAULT 0,
	`behavioralScore` int DEFAULT 0,
	`engagementScore` int DEFAULT 0,
	`timingScore` int DEFAULT 0,
	`socialScore` int DEFAULT 0,
	`contentScore` int DEFAULT 0,
	`recencyScore` int DEFAULT 0,
	`frequencyScore` int DEFAULT 0,
	`monetaryScore` int DEFAULT 0,
	`channelScore` int DEFAULT 0,
	`intentScore` int DEFAULT 0,
	`relationshipScore` int DEFAULT 0,
	`totalScore` int DEFAULT 0,
	`scoreGrade` varchar(4),
	`scoreExplanation` text,
	`topStrengths` json,
	`topWeaknesses` json,
	`recommendedActions` json,
	`predictedConversionProb` int DEFAULT 0,
	`predictedDealValue` bigint,
	`optimalContactTime` varchar(256),
	`optimalChannel` varchar(256),
	`lastScoredAt` bigint NOT NULL,
	`scoringVersion` int DEFAULT 1,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `prospect_scores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prospects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`contactId` int,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128),
	`email` varchar(320),
	`jobTitle` varchar(256),
	`companyName` varchar(256),
	`companyDomain` varchar(256),
	`linkedinUrl` varchar(512),
	`phone` varchar(64),
	`location` varchar(256),
	`industry` varchar(128),
	`sourceType` varchar(64) NOT NULL,
	`sourceSignalId` int,
	`apolloId` varchar(128),
	`verificationStatus` varchar(32) NOT NULL DEFAULT 'pending',
	`verificationProvider` varchar(32),
	`verifiedAt` bigint,
	`bounceRisk` varchar(16),
	`psychographicProfile` json,
	`socialPosts` json,
	`engagementStage` varchar(32) NOT NULL DEFAULT 'discovered',
	`ghostSequenceId` int,
	`currentSequenceStep` int DEFAULT 0,
	`lastOutreachAt` bigint,
	`repliedAt` bigint,
	`replyContent` text,
	`intentScore` int DEFAULT 0,
	`intentSignal` varchar(64),
	`lastLinkedinCheckAt` bigint,
	`previousCompany` varchar(256),
	`previousJobTitle` varchar(256),
	`jobChangeDetectedAt` bigint,
	`selfHealingAttempts` int DEFAULT 0,
	`battleCardId` int,
	`tags` json,
	`notes` text,
	`score` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `prospects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sender_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(256) NOT NULL,
	`physicalAddress` text NOT NULL,
	`city` varchar(128),
	`state` varchar(64),
	`zipCode` varchar(16),
	`country` varchar(64),
	`defaultFromName` varchar(256),
	`defaultReplyTo` varchar(320),
	`unsubscribeUrl` varchar(1024),
	`privacyPolicyUrl` varchar(1024),
	`outlookThrottlePerMinute` int DEFAULT 10,
	`gmailThrottlePerMinute` int DEFAULT 20,
	`yahooThrottlePerMinute` int DEFAULT 15,
	`defaultThrottlePerMinute` int DEFAULT 30,
	`maxBounceRatePercent` int DEFAULT 2,
	`maxComplaintRatePercent` int DEFAULT 1,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `sender_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppression_list` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`email` varchar(320) NOT NULL,
	`reason` varchar(64) NOT NULL,
	`source` varchar(64),
	`campaignId` int,
	`notes` text,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `suppression_list_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trigger_signals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`signalType` varchar(64) NOT NULL,
	`title` varchar(512) NOT NULL,
	`description` text,
	`sourceUrl` varchar(1024),
	`sourcePlatform` varchar(64),
	`prospectId` int,
	`companyName` varchar(256),
	`personName` varchar(256),
	`signalStatus` varchar(32) NOT NULL DEFAULT 'new',
	`priority` varchar(16) DEFAULT 'medium',
	`actionTaken` text,
	`processedAt` bigint,
	`expiresAt` bigint,
	`metadata` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `trigger_signals_id` PRIMARY KEY(`id`)
);
