CREATE TABLE `domain_health_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`domainHealthId` int NOT NULL,
	`domain` varchar(256) NOT NULL,
	`recordDate` varchar(16) NOT NULL,
	`healthScore` int NOT NULL DEFAULT 50,
	`spfStatus` varchar(16) DEFAULT 'unknown',
	`dkimStatus` varchar(16) DEFAULT 'unknown',
	`dmarcStatus` varchar(16) DEFAULT 'unknown',
	`totalSent` int NOT NULL DEFAULT 0,
	`totalDelivered` int NOT NULL DEFAULT 0,
	`totalBounced` int NOT NULL DEFAULT 0,
	`totalComplaints` int NOT NULL DEFAULT 0,
	`totalOpens` int NOT NULL DEFAULT 0,
	`totalClicks` int NOT NULL DEFAULT 0,
	`bounceRate` int DEFAULT 0,
	`complaintRate` int DEFAULT 0,
	`openRate` int DEFAULT 0,
	`clickRate` int DEFAULT 0,
	`deliveryRate` int DEFAULT 10000,
	`warmupDay` int DEFAULT 0,
	`warmupPhase` int DEFAULT 0,
	`dailySendLimit` int DEFAULT 50,
	`providerBreakdown` json,
	`isPaused` boolean NOT NULL DEFAULT false,
	`pauseReason` varchar(256),
	`recommendations` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `domain_health_records_id` PRIMARY KEY(`id`)
);
