CREATE TABLE `call_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`voiceCampaignId` int,
	`contactId` int,
	`prospectId` int,
	`phoneNumber` varchar(64) NOT NULL,
	`callDirection` enum('outbound','inbound') NOT NULL DEFAULT 'outbound',
	`callStatus` enum('queued','ringing','in_progress','completed','no_answer','busy','failed','voicemail') NOT NULL DEFAULT 'queued',
	`callStartedAt` bigint,
	`connectedAt` bigint,
	`callEndedAt` bigint,
	`durationSeconds` int DEFAULT 0,
	`transcription` text,
	`conversationSummary` text,
	`aiSentiment` varchar(32),
	`qualificationScore` int DEFAULT 0,
	`qualResult` enum('qualified','not_qualified','needs_followup','not_reached','pending') NOT NULL DEFAULT 'pending',
	`qualificationDetails` json,
	`appointmentBooked` boolean DEFAULT false,
	`appointmentDate` bigint,
	`appointmentNotes` text,
	`followUpRequired` boolean DEFAULT false,
	`followUpDate` bigint,
	`followUpNotes` text,
	`recordingUrl` varchar(1024),
	`attemptNumber` int DEFAULT 1,
	`previousCallId` int,
	`taskId` int,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `call_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `carrier_packets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`carrierName` varchar(256) NOT NULL,
	`mcNumber` varchar(32),
	`dotNumber` varchar(32),
	`companyId` int,
	`contactId` int,
	`cpAuthorityStatus` varchar(32) DEFAULT 'pending',
	`cpAuthorityType` varchar(64),
	`saferRating` varchar(32),
	`insuranceProvider` varchar(256),
	`insurancePolicyNumber` varchar(128),
	`insuranceExpiresAt` bigint,
	`cargoInsuranceAmount` int,
	`liabilityInsuranceAmount` int,
	`autoInsuranceAmount` int,
	`workersCompAmount` int,
	`w9Status` varchar(32) DEFAULT 'missing',
	`w9FileId` int,
	`taxId` varchar(32),
	`equipmentTypes` json,
	`serviceAreas` json,
	`operatingRadius` varchar(64),
	`fleetSize` int,
	`yearsInBusiness` int,
	`agreementStatus` varchar(32) DEFAULT 'pending',
	`agreementSignedAt` bigint,
	`agreementExpiresAt` bigint,
	`agreementFileId` int,
	`paymentTerms` varchar(64),
	`factoringCompany` varchar(256),
	`complianceScore` int DEFAULT 0,
	`complianceChecklist` json,
	`packetStatus` enum('incomplete','pending_review','approved','rejected','expired') NOT NULL DEFAULT 'incomplete',
	`reviewNotes` text,
	`approvedBy` int,
	`approvedAt` bigint,
	`cpTags` json,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `carrier_packets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deal_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` int NOT NULL,
	`userId` int NOT NULL,
	`winProbability` int NOT NULL DEFAULT 50,
	`previousProbability` int,
	`probabilityTrend` varchar(16),
	`engagementSignal` int DEFAULT 50,
	`responseTimeSignal` int DEFAULT 50,
	`meetingFrequencySignal` int DEFAULT 50,
	`stakeholderSignal` int DEFAULT 50,
	`competitiveSignal` int DEFAULT 50,
	`budgetSignal` int DEFAULT 50,
	`timelineSignal` int DEFAULT 50,
	`championSignal` int DEFAULT 50,
	`aiExplanation` text,
	`riskFactors` json,
	`positiveIndicators` json,
	`dsRecommendedActions` json,
	`forecastedValue` bigint,
	`weightedValue` bigint,
	`expectedCloseDate` bigint,
	`scoredAt` bigint NOT NULL,
	`dsScoringVersion` int DEFAULT 1,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `deal_scores_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(512) NOT NULL,
	`fileUrl` varchar(1024) NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`mimeType` varchar(128),
	`fileSizeBytes` int,
	`documentType` varchar(64) NOT NULL,
	`docCategory` varchar(64) DEFAULT 'general',
	`extractedData` json,
	`extractionStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`extractionConfidence` int DEFAULT 0,
	`extractionErrors` json,
	`contactId` int,
	`companyId` int,
	`dealId` int,
	`carrierPacketId` int,
	`isValid` boolean,
	`validationNotes` text,
	`docExpiresAt` bigint,
	`docTags` json,
	`docNotes` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meeting_preps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`mpContactId` int,
	`mpCompanyId` int,
	`mpDealId` int,
	`briefTitle` varchar(256) NOT NULL,
	`contactSummary` text,
	`companySummary` text,
	`dealContext` text,
	`recentActivity` json,
	`talkingPoints` json,
	`questionsToAsk` json,
	`potentialObjections` json,
	`mpCompetitorIntel` text,
	`meetingDate` bigint,
	`mpGeneratedAt` bigint NOT NULL,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `meeting_preps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `revenue_briefings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`briefingDate` varchar(16) NOT NULL,
	`summary` text NOT NULL,
	`revenueAtRisk` bigint,
	`revenueOpportunity` bigint,
	`actions` json,
	`weeklyMetrics` json,
	`isRead` boolean NOT NULL DEFAULT false,
	`actionsCompleted` int DEFAULT 0,
	`totalActions` int DEFAULT 0,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `revenue_briefings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `smart_notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`notifTitle` varchar(256) NOT NULL,
	`notifMessage` text NOT NULL,
	`notifType` varchar(64) NOT NULL,
	`notifPriority` varchar(16) NOT NULL DEFAULT 'medium',
	`estimatedRevenue` bigint,
	`urgencyScore` int DEFAULT 50,
	`notifContactId` int,
	`notifDealId` int,
	`notifCompanyId` int,
	`actionUrl` varchar(512),
	`actionLabel` varchar(128),
	`notifIsRead` boolean NOT NULL DEFAULT false,
	`isDismissed` boolean NOT NULL DEFAULT false,
	`readAt` bigint,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `smart_notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `voice_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`scriptTemplate` text,
	`objective` varchar(128) NOT NULL DEFAULT 'qualify_lead',
	`voicePersona` varchar(64) DEFAULT 'professional',
	`industry` varchar(128) DEFAULT 'freight_brokerage',
	`targetSegmentId` int,
	`targetContactIds` json,
	`callWindowStart` varchar(8) DEFAULT '09:00',
	`callWindowEnd` varchar(8) DEFAULT '17:00',
	`callWindowTimezone` varchar(64) DEFAULT 'America/New_York',
	`maxConcurrentCalls` int DEFAULT 10,
	`maxCallsPerDay` int DEFAULT 500,
	`maxRetries` int DEFAULT 3,
	`retryDelayMinutes` int DEFAULT 60,
	`qualificationCriteria` json,
	`totalCalls` int DEFAULT 0,
	`totalConnected` int DEFAULT 0,
	`totalQualified` int DEFAULT 0,
	`totalAppointments` int DEFAULT 0,
	`avgCallDuration` int DEFAULT 0,
	`vcStatus` enum('draft','active','paused','completed','archived') NOT NULL DEFAULT 'draft',
	`startedAt` bigint,
	`completedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `voice_campaigns_id` PRIMARY KEY(`id`)
);
