CREATE TABLE `b2b_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`b2bUserId` int NOT NULL,
	`b2bFirstName` varchar(128),
	`b2bLastName` varchar(128),
	`b2bEmail` varchar(256),
	`b2bPhone` varchar(64),
	`b2bJobTitle` varchar(256),
	`b2bLinkedinUrl` varchar(512),
	`b2bCompanyName` varchar(256),
	`b2bCompanyDomain` varchar(256),
	`b2bIndustry` varchar(128),
	`b2bCompanySize` varchar(64),
	`b2bRevenue` varchar(64),
	`b2bLocation` varchar(256),
	`enrichmentSource` varchar(64),
	`enrichedAt` bigint,
	`b2bConfidence` int,
	`b2bImported` boolean DEFAULT false,
	`importedContactId` int,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `b2b_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `call_recordings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`crUserId` int NOT NULL,
	`crCallLogId` int,
	`crContactId` int,
	`crDealId` int,
	`recordingUrl` text,
	`crDuration` int,
	`crDirection` varchar(16),
	`analyzed` boolean DEFAULT false,
	`crTranscript` text,
	`crSummary` text,
	`sentiment` varchar(16),
	`sentimentScore` int,
	`talkToListenRatio` varchar(16),
	`keyTopics` json,
	`crActionItems` json,
	`crObjections` json,
	`competitorMentions` json,
	`crNextSteps` json,
	`coachingInsights` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `call_recordings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `carrier_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cpUserId` int NOT NULL,
	`cpCompanyId` int,
	`cpCarrierPacketId` int,
	`cpCarrierName` varchar(256) NOT NULL,
	`cpDotNumber` varchar(32),
	`cpMcNumber` varchar(32),
	`scacCode` varchar(16),
	`authorityStatus` varchar(32),
	`authorityGrantDate` bigint,
	`safetyRating` varchar(32),
	`safetyRatingDate` bigint,
	`operatingStatus` varchar(32),
	`outOfServiceDate` bigint,
	`insuranceOnFile` boolean DEFAULT false,
	`insuranceExpiry` bigint,
	`liabilityAmount` bigint,
	`cargoInsurance` bigint,
	`bondSurety` varchar(256),
	`totalDrivers` int,
	`totalPowerUnits` int,
	`totalTrailers` int,
	`onTimePickupRate` int,
	`onTimeDeliveryRate` int,
	`claimsRatio` varchar(16),
	`avgResponseTime` int,
	`totalLoadsCompleted` int DEFAULT 0,
	`totalLoadsDeclined` int DEFAULT 0,
	`overallScore` int,
	`preferredLanes` json,
	`cpEquipmentTypes` json,
	`serviceAreas` json,
	`vetStatus` varchar(32) DEFAULT 'pending',
	`vetNotes` text,
	`lastVetDate` bigint,
	`autoFlagged` boolean DEFAULT false,
	`flagReason` text,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `carrier_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `enrichment_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`elUserId` int NOT NULL,
	`entityType` varchar(32),
	`entityId` int,
	`elSource` varchar(64),
	`fieldsEnriched` json,
	`previousData` json,
	`newData` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `enrichment_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inbound_emails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ieUserId` int NOT NULL,
	`ieFromEmail` varchar(256),
	`ieFromName` varchar(256),
	`ieSubject` varchar(512),
	`ieBodyText` text,
	`ieBodyHtml` text,
	`ieReceivedAt` bigint NOT NULL,
	`ieParsed` boolean DEFAULT false,
	`parsedData` json,
	`parseConfidence` int,
	`convertedToLoad` boolean DEFAULT false,
	`ieLoadId` int,
	`ieContactId` int,
	`ieStatus` varchar(32) DEFAULT 'new',
	`createdAt` bigint NOT NULL,
	CONSTRAINT `inbound_emails_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invUserId` int NOT NULL,
	`invLoadId` int,
	`billToCompanyId` int,
	`billToContactId` int,
	`billToName` varchar(256),
	`billToAddress` text,
	`billToEmail` varchar(256),
	`payToName` varchar(256),
	`payToAddress` text,
	`invoiceNumber` varchar(64) NOT NULL,
	`invStatus` varchar(32) DEFAULT 'draft',
	`issueDate` bigint NOT NULL,
	`dueDate` bigint,
	`paidDate` bigint,
	`lineItems` json,
	`subtotal` bigint,
	`taxRate` varchar(16),
	`taxAmount` bigint,
	`totalAmount` bigint NOT NULL,
	`amountPaid` bigint DEFAULT 0,
	`balanceDue` bigint,
	`paymentTerms` varchar(64) DEFAULT 'Net 30',
	`paymentMethod` varchar(32),
	`paymentReference` varchar(128),
	`invNotes` text,
	`invInternalMemo` text,
	`pdfUrl` text,
	`sentAt` bigint,
	`viewedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `load_board_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lbpUserId` int NOT NULL,
	`lbpLoadId` int NOT NULL,
	`board` varchar(32) NOT NULL,
	`externalPostId` varchar(128),
	`lbpStatus` varchar(32) DEFAULT 'active',
	`postedAt` bigint NOT NULL,
	`expiresAt` bigint,
	`views` int DEFAULT 0,
	`responses` int DEFAULT 0,
	`responseData` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `load_board_posts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `load_status_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`lshUserId` int NOT NULL,
	`fromStatus` varchar(32),
	`toStatus` varchar(32) NOT NULL,
	`lshNotes` text,
	`lshLocation` varchar(256),
	`createdAt` bigint NOT NULL,
	CONSTRAINT `load_status_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `loads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`loadCompanyId` int,
	`loadContactId` int,
	`loadCarrierId` int,
	`referenceNumber` varchar(64) NOT NULL,
	`loadStatus` varchar(32) NOT NULL DEFAULT 'draft',
	`loadType` varchar(32) DEFAULT 'FTL',
	`commodity` varchar(256),
	`weight` int,
	`weightUnit` varchar(16) DEFAULT 'lbs',
	`pieces` int,
	`pallets` int,
	`dimensions` varchar(128),
	`equipmentType` varchar(64),
	`temperatureMin` int,
	`temperatureMax` int,
	`hazmat` boolean DEFAULT false,
	`originCity` varchar(128),
	`originState` varchar(64),
	`originZip` varchar(16),
	`originAddress` text,
	`originLat` varchar(32),
	`originLng` varchar(32),
	`destCity` varchar(128),
	`destState` varchar(64),
	`destZip` varchar(16),
	`destAddress` text,
	`destLat` varchar(32),
	`destLng` varchar(32),
	`pickupDate` bigint,
	`pickupWindowStart` bigint,
	`pickupWindowEnd` bigint,
	`deliveryDate` bigint,
	`deliveryWindowStart` bigint,
	`deliveryWindowEnd` bigint,
	`actualPickup` bigint,
	`actualDelivery` bigint,
	`customerRate` bigint,
	`carrierRate` bigint,
	`margin` bigint,
	`marginPercent` varchar(16),
	`currentLocation` varchar(256),
	`lastCheckIn` bigint,
	`estimatedArrival` bigint,
	`trackingNotes` text,
	`bolNumber` varchar(64),
	`proNumber` varchar(64),
	`poNumber` varchar(64),
	`loadDealId` int,
	`loadInvoiceId` int,
	`specialInstructions` text,
	`internalNotes` text,
	`miles` int,
	`ratePerMile` varchar(16),
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `loads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `migration_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mjUserId` int NOT NULL,
	`mjCompanyId` int,
	`sourcePlatform` varchar(64) NOT NULL,
	`sourceCredentials` text,
	`mjStatus` varchar(32) DEFAULT 'pending',
	`totalRecords` int DEFAULT 0,
	`importedRecords` int DEFAULT 0,
	`failedRecords` int DEFAULT 0,
	`skippedRecords` int DEFAULT 0,
	`entityTypes` json,
	`fieldMapping` json,
	`importLog` json,
	`errorDetails` json,
	`mjStartedAt` bigint,
	`mjCompletedAt` bigint,
	`estimatedTimeRemaining` int,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `migration_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `onboarding_flows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ofUserId` int NOT NULL,
	`ofCompanyId` int,
	`flowName` varchar(256) NOT NULL,
	`flowType` varchar(32) DEFAULT 'shipper',
	`ofIsActive` boolean DEFAULT true,
	`ofSteps` json,
	`requireSignature` boolean DEFAULT true,
	`autoCreateContact` boolean DEFAULT true,
	`autoCreateCompany` boolean DEFAULT true,
	`notifyOnComplete` boolean DEFAULT true,
	`ofWelcomeMessage` text,
	`completionMessage` text,
	`createdAt` bigint NOT NULL,
	`createdAt2` bigint NOT NULL,
	CONSTRAINT `onboarding_flows_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `onboarding_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`osFlowId` int NOT NULL,
	`osUserId` int,
	`submitterName` varchar(256),
	`submitterEmail` varchar(256),
	`submitterPhone` varchar(64),
	`submitterCompany` varchar(256),
	`currentStep` int DEFAULT 0,
	`totalSteps` int,
	`osStatus` varchar(32) DEFAULT 'in_progress',
	`formData` json,
	`signatureUrl` text,
	`signedAt` bigint,
	`signedIp` varchar(64),
	`createdContactId` int,
	`createdCompanyId` int,
	`reviewedBy` int,
	`osReviewNotes` text,
	`osCompletedAt` bigint,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `onboarding_submissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portal_access` (
	`id` int AUTO_INCREMENT NOT NULL,
	`paContactId` int NOT NULL,
	`paCompanyId` int,
	`paEmail` varchar(256) NOT NULL,
	`passwordHash` varchar(512),
	`paAccessToken` varchar(512),
	`paIsActive` boolean DEFAULT true,
	`paLastLogin` bigint,
	`paPermissions` json,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `portal_access_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portal_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`portalUserId` int NOT NULL,
	`pqCompanyId` int,
	`pqOriginCity` varchar(128),
	`pqOriginState` varchar(64),
	`pqOriginZip` varchar(16),
	`pqDestCity` varchar(128),
	`pqDestState` varchar(64),
	`pqDestZip` varchar(16),
	`pqCommodity` varchar(256),
	`pqWeight` int,
	`pqEquipmentType` varchar(64),
	`pqPickupDate` bigint,
	`pqDeliveryDate` bigint,
	`pqSpecialInstructions` text,
	`pqStatus` varchar(32) DEFAULT 'pending',
	`quotedRate` bigint,
	`quotedBy` int,
	`quotedAt` bigint,
	`respondedAt` bigint,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `portal_quotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscription_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spName` varchar(128) NOT NULL,
	`tier` varchar(32) NOT NULL,
	`pricePerUser` int NOT NULL,
	`maxUsers` int,
	`spFeatures` json,
	`spDescription` text,
	`spIsActive` boolean DEFAULT true,
	`trialDays` int DEFAULT 60,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `subscription_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tenant_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tsCompanyId` int NOT NULL,
	`tsPlanId` int NOT NULL,
	`tsStatus` varchar(32) DEFAULT 'trial',
	`trialStart` bigint,
	`trialEnd` bigint,
	`billingStart` bigint,
	`currentPeriodStart` bigint,
	`currentPeriodEnd` bigint,
	`cancelledAt` bigint,
	`stripeCustomerId` varchar(128),
	`stripeSubscriptionId` varchar(128),
	`currentUsers` int DEFAULT 1,
	`monthlyAmount` int,
	`createdAt` bigint NOT NULL,
	`tsUpdatedAt` bigint NOT NULL,
	CONSTRAINT `tenant_subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visitor_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vsUserId` int NOT NULL,
	`visitorId` varchar(128) NOT NULL,
	`vsIpAddress` varchar(64),
	`vsUserAgent` text,
	`vsReferrer` text,
	`identifiedCompany` varchar(256),
	`identifiedDomain` varchar(256),
	`identifiedIndustry` varchar(128),
	`identifiedSize` varchar(64),
	`identificationConfidence` int,
	`pagesViewed` json,
	`totalPageViews` int DEFAULT 1,
	`totalDuration` int DEFAULT 0,
	`firstVisit` bigint NOT NULL,
	`lastVisit` bigint NOT NULL,
	`visitCount` int DEFAULT 1,
	`convertedToProspect` boolean DEFAULT false,
	`vsProspectId` int,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `visitor_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `warmup_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`wuUserId` int NOT NULL,
	`wuSmtpAccountId` int NOT NULL,
	`wuDomain` varchar(256) NOT NULL,
	`dailyTarget` int DEFAULT 5,
	`currentDaily` int DEFAULT 1,
	`rampUpRate` int DEFAULT 2,
	`maxDaily` int DEFAULT 50,
	`wuStatus` varchar(32) DEFAULT 'active',
	`wuStartDate` bigint NOT NULL,
	`wuEndDate` bigint,
	`currentDay` int DEFAULT 1,
	`wuTotalSent` int DEFAULT 0,
	`wuTotalReceived` int DEFAULT 0,
	`wuTotalReplied` int DEFAULT 0,
	`inboxRate` int,
	`spamRate` int,
	`wuBounceRate` int,
	`reputationScore` int,
	`createdAt` bigint NOT NULL,
	`createdAt2` bigint NOT NULL,
	CONSTRAINT `warmup_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `white_label_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`wlCompanyId` int NOT NULL,
	`brandName` varchar(256) NOT NULL,
	`wlLogoUrl` text,
	`faviconUrl` text,
	`primaryColor` varchar(16),
	`secondaryColor` varchar(16),
	`accentColor` varchar(16),
	`wlBackgroundColor` varchar(16),
	`sidebarColor` varchar(16),
	`customDomain` varchar(256),
	`customDomainVerified` boolean DEFAULT false,
	`wlEmailFromName` varchar(128),
	`wlEmailFooter` text,
	`portalWelcomeMessage` text,
	`portalHelpText` text,
	`showPoweredBy` boolean DEFAULT true,
	`customCss` text,
	`wlIsActive` boolean DEFAULT false,
	`createdAt` bigint NOT NULL,
	`createdAt2` bigint NOT NULL,
	CONSTRAINT `white_label_config_id` PRIMARY KEY(`id`)
);
