CREATE TABLE `consolidation_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`groupId` varchar(50) NOT NULL,
	`status` varchar(20) NOT NULL DEFAULT 'identified',
	`originRegion` varchar(100) NOT NULL,
	`destRegion` varchar(100) NOT NULL,
	`loadIds` json NOT NULL,
	`loadCount` int NOT NULL,
	`individualCost` decimal(12,2) NOT NULL,
	`consolidatedCost` decimal(12,2) NOT NULL,
	`savings` decimal(12,2) NOT NULL,
	`savingsPercent` decimal(5,2),
	`totalWeight` decimal(12,2),
	`capacityUtilization` decimal(5,2),
	`equipmentType` varchar(50),
	`aiReasoning` text,
	`confidenceScore` decimal(5,2),
	`windowStart` bigint,
	`windowEnd` bigint,
	`expiresAt` bigint,
	`executedAt` bigint,
	`createdAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `consolidation_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lane_analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`originCity` varchar(100) NOT NULL,
	`originState` varchar(50) NOT NULL,
	`destCity` varchar(100) NOT NULL,
	`destState` varchar(50) NOT NULL,
	`equipmentType` varchar(50) NOT NULL,
	`totalLoads` int NOT NULL DEFAULT 0,
	`avgRate` decimal(12,2),
	`minRate` decimal(12,2),
	`maxRate` decimal(12,2),
	`avgMargin` decimal(5,2),
	`demandScore` decimal(5,2),
	`demandTrend` varchar(20),
	`seasonalFactor` decimal(4,2),
	`nextWeekPrediction` int,
	`availableCarriers` int DEFAULT 0,
	`avgTransitHours` decimal(6,1),
	`distanceMiles` decimal(10,2),
	`periodStart` bigint NOT NULL,
	`periodEnd` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `lane_analytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marketplace_bids` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`carrierId` int,
	`carrierName` varchar(255) NOT NULL,
	`carrierDot` varchar(20),
	`carrierMc` varchar(20),
	`carrierEmail` varchar(255),
	`carrierPhone` varchar(50),
	`bidRate` decimal(12,2) NOT NULL,
	`estimatedPickup` bigint,
	`estimatedDelivery` bigint,
	`equipmentType` varchar(50),
	`driverName` varchar(255),
	`driverPhone` varchar(50),
	`truckNumber` varchar(50),
	`trailerNumber` varchar(50),
	`insuranceVerified` boolean DEFAULT false,
	`safetyRating` varchar(20),
	`matchScore` decimal(5,2),
	`status` varchar(20) NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `marketplace_bids_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marketplace_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`docType` varchar(30) NOT NULL,
	`title` varchar(255) NOT NULL,
	`status` varchar(20) NOT NULL DEFAULT 'generated',
	`fileUrl` text,
	`fileKey` varchar(255),
	`generatedBy` varchar(20) NOT NULL DEFAULT 'ai',
	`signedBy` varchar(255),
	`signedAt` bigint,
	`expiresAt` bigint,
	`metadata` json,
	`createdAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `marketplace_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marketplace_loads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shipperUserId` varchar(255),
	`shipperCompanyName` varchar(255) NOT NULL,
	`shipperContactName` varchar(255) NOT NULL,
	`shipperEmail` varchar(255) NOT NULL,
	`shipperPhone` varchar(50),
	`loadNumber` varchar(50) NOT NULL,
	`commodity` varchar(255) NOT NULL,
	`weight` decimal(10,2) NOT NULL,
	`pieces` int,
	`pallets` int,
	`lengthInches` decimal(10,2),
	`widthInches` decimal(10,2),
	`heightInches` decimal(10,2),
	`equipmentType` varchar(50) NOT NULL,
	`specialRequirements` text,
	`hazmat` boolean DEFAULT false,
	`temperatureControlled` boolean DEFAULT false,
	`tempMin` decimal(5,1),
	`tempMax` decimal(5,1),
	`originCity` varchar(100) NOT NULL,
	`originState` varchar(50) NOT NULL,
	`originZip` varchar(20) NOT NULL,
	`originAddress` text,
	`pickupDate` bigint NOT NULL,
	`pickupWindowStart` varchar(10),
	`pickupWindowEnd` varchar(10),
	`destCity` varchar(100) NOT NULL,
	`destState` varchar(50) NOT NULL,
	`destZip` varchar(20) NOT NULL,
	`destAddress` text,
	`deliveryDate` bigint NOT NULL,
	`deliveryWindowStart` varchar(10),
	`deliveryWindowEnd` varchar(10),
	`shipperRate` decimal(12,2),
	`carrierRate` decimal(12,2),
	`margin` decimal(12,2),
	`marginPercent` decimal(5,2),
	`status` varchar(30) NOT NULL DEFAULT 'posted',
	`matchedCarrierId` int,
	`matchedCarrierName` varchar(255),
	`matchedCarrierDot` varchar(20),
	`matchedCarrierMc` varchar(20),
	`matchScore` decimal(5,2),
	`distanceMiles` decimal(10,2),
	`estimatedTransitHours` decimal(6,1),
	`isConsolidated` boolean DEFAULT false,
	`consolidationGroupId` int,
	`bookedAt` bigint,
	`dispatchedAt` bigint,
	`pickedUpAt` bigint,
	`deliveredAt` bigint,
	`completedAt` bigint,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `marketplace_loads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marketplace_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`shipperPaymentStatus` varchar(20) NOT NULL DEFAULT 'pending',
	`shipperAmount` decimal(12,2) NOT NULL,
	`shipperPaymentMethod` varchar(30),
	`shipperPaymentRef` varchar(100),
	`shipperPaidAt` bigint,
	`carrierPaymentStatus` varchar(20) NOT NULL DEFAULT 'pending',
	`carrierAmount` decimal(12,2) NOT NULL,
	`carrierPaymentMethod` varchar(30),
	`carrierPaymentRef` varchar(100),
	`carrierPaidAt` bigint,
	`grossMargin` decimal(12,2),
	`marginPercent` decimal(5,2),
	`escrowStatus` varchar(20) NOT NULL DEFAULT 'unfunded',
	`escrowFundedAt` bigint,
	`escrowReleasedAt` bigint,
	`invoiceNumber` varchar(50),
	`invoiceGeneratedAt` bigint,
	`createdAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `marketplace_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `marketplace_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loadId` int NOT NULL,
	`eventType` varchar(30) NOT NULL,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`city` varchar(100),
	`state` varchar(50),
	`description` text,
	`currentEta` bigint,
	`milesRemaining` decimal(10,2),
	`speedMph` decimal(5,1),
	`heading` varchar(10),
	`temperature` decimal(5,1),
	`createdAt` bigint NOT NULL,
	`companyId` int,
	CONSTRAINT `marketplace_tracking_id` PRIMARY KEY(`id`)
);
